## 1.0.0
CREATE TABLE AIPRO_QJDST(
`NAME` VARCHAR(510) NULL COMMENT '姓名',
`NUM` VARCHAR(510) NULL COMMENT '工号',
`OPTIME` DATETIME(6) NULL COMMENT '入职时间',
`GSNUM` DECIMAL(21,2) NULL COMMENT '可用假期',
`STARTTIME` DATETIME(6) NULL COMMENT '请假开始时间',
`ENDTIME` DATETIME(6) NULL COMMENT '请假结束时间',
`COMPANY_CODE` VARCHAR(255) NULL COMMENT '公司编码',
`CREATE_TIME` DATETIME(6) NULL COMMENT '创建时间',
`MODIFY_TIME` DATETIME(6) NULL COMMENT '修改时间',
`DELETE_TIME` DATETIME(6) NULL COMMENT '删除时间',
`SORT` DECIMAL(19) NULL COMMENT '排序',
`PROCESS_KEY` VARCHAR(255) NULL COMMENT '流程key',
`PROCESS_ID` VARCHAR(255) NULL COMMENT '流程实例id',
`FORM_NO` VARCHAR(255) NULL COMMENT '流程单据编号',
`PROCESS_TASK_I18N` VARCHAR(255) NULL COMMENT '流程单据状态',
`PROCESS_STATUS` VARCHAR(50) NULL COMMENT '流程状态',
`PROCESS_NAME` VARCHAR(100) NULL COMMENT '流程名称',
`PROCESS_VERSION` VARCHAR(20) NULL COMMENT '流程版本',
`EFFECT_TIME` DATETIME(6) NULL COMMENT '生效时间',
`ID` DECIMAL(19) NOT NULL PRIMARY KEY COMMENT '主键ID',
`VERSION` DECIMAL(5) NULL COMMENT '版本号',
`VALID` DECIMAL(1) DEFAULT 1 NOT NULL COMMENT '是否有效',
`POS_LAY_REC` VARCHAR(255) NULL COMMENT '岗位层级',
`OWNER_POS_CODE` VARCHAR(255) NULL COMMENT '所有者岗位编码',
`OWNER_POS_NAME` VARCHAR(255) NULL COMMENT '所有者岗位名称',
`CREATE_POS_CODE` VARCHAR(255) NULL COMMENT '创建人岗位编码',
`CREATE_POS_NAME` VARCHAR(255) NULL COMMENT '创建人岗位名称',
`OWNER_STAFF_CODE` VARCHAR(50) NULL COMMENT '所有者员工编码',
`OWNER_STAFF_NAME` VARCHAR(250) NULL COMMENT '所有者员工名称',
`DELETE_STAFF_CODE` VARCHAR(50) NULL COMMENT '删除人编码',
`DELETE_STAFF_NAME` VARCHAR(250) NULL COMMENT '删除人名称',
`MODIFY_STAFF_CODE` VARCHAR(50) NULL COMMENT '修改人编码',
`MODIFY_STAFF_NAME` VARCHAR(250) NULL COMMENT '修改人名称',
`CREATE_STAFF_CODE` VARCHAR(50) NULL COMMENT '创建人编码',
`CREATE_STAFF_NAME` VARCHAR(250) NULL COMMENT '创建人名称',
`OWNER_DEPT_CODE` VARCHAR(255) NULL COMMENT '所有者部门编码',
`OWNER_DEPT_NAME` VARCHAR(255) NULL COMMENT '所有者部门名称'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE INDEX INDEX_AIPRO_QJDST_VALID_COMPANY_CODE USING BTREE ON AIPRO_QJDST(`VALID`,`COMPANY_CODE`,`CREATE_TIME`);
ALTER TABLE AIPRO_QJDST ADD NAME VARCHAR(510) NULL COMMENT '姓名';
ALTER TABLE AIPRO_QJDST ADD NUM VARCHAR(510) NULL COMMENT '工号';
ALTER TABLE AIPRO_QJDST ADD OPTIME DATETIME(6) NULL COMMENT '入职时间';
ALTER TABLE AIPRO_QJDST ADD GSNUM DECIMAL(21,2) NULL COMMENT '可用假期';
ALTER TABLE AIPRO_QJDST ADD STARTTIME DATETIME(6) NULL COMMENT '请假开始时间';
ALTER TABLE AIPRO_QJDST ADD ENDTIME DATETIME(6) NULL COMMENT '请假结束时间';
ALTER TABLE AIPRO_QJDST ADD COMPANY_CODE VARCHAR(255) NULL COMMENT '公司编码';
ALTER TABLE AIPRO_QJDST ADD CREATE_TIME DATETIME(6) NULL COMMENT '创建时间';
ALTER TABLE AIPRO_QJDST ADD MODIFY_TIME DATETIME(6) NULL COMMENT '修改时间';
ALTER TABLE AIPRO_QJDST ADD DELETE_TIME DATETIME(6) NULL COMMENT '删除时间';
ALTER TABLE AIPRO_QJDST ADD SORT DECIMAL(19) NULL COMMENT '排序';
ALTER TABLE AIPRO_QJDST ADD PROCESS_KEY VARCHAR(255) NULL COMMENT '流程key';
ALTER TABLE AIPRO_QJDST ADD PROCESS_ID VARCHAR(255) NULL COMMENT '流程实例id';
ALTER TABLE AIPRO_QJDST ADD FORM_NO VARCHAR(255) NULL COMMENT '流程单据编号';
ALTER TABLE AIPRO_QJDST ADD PROCESS_TASK_I18N VARCHAR(255) NULL COMMENT '流程单据状态';
ALTER TABLE AIPRO_QJDST ADD PROCESS_STATUS VARCHAR(50) NULL COMMENT '流程状态';
ALTER TABLE AIPRO_QJDST ADD PROCESS_NAME VARCHAR(100) NULL COMMENT '流程名称';
ALTER TABLE AIPRO_QJDST ADD PROCESS_VERSION VARCHAR(20) NULL COMMENT '流程版本';
ALTER TABLE AIPRO_QJDST ADD EFFECT_TIME DATETIME(6) NULL COMMENT '生效时间';
ALTER TABLE AIPRO_QJDST ADD ID DECIMAL(19) NULL PRIMARY KEY COMMENT '主键ID';
ALTER TABLE AIPRO_QJDST MODIFY ID DECIMAL(19) NOT NULL PRIMARY KEY COMMENT '主键ID';
ALTER TABLE AIPRO_QJDST ADD VERSION DECIMAL(5) NULL COMMENT '版本号';
ALTER TABLE AIPRO_QJDST ADD VALID DECIMAL(1) DEFAULT 1 NULL COMMENT '是否有效';
ALTER TABLE AIPRO_QJDST MODIFY VALID DECIMAL(1) DEFAULT 1 NOT NULL COMMENT '是否有效';
ALTER TABLE AIPRO_QJDST ADD POS_LAY_REC VARCHAR(255) NULL COMMENT '岗位层级';
ALTER TABLE AIPRO_QJDST ADD OWNER_POS_CODE VARCHAR(255) NULL COMMENT '所有者岗位编码';
ALTER TABLE AIPRO_QJDST ADD OWNER_POS_NAME VARCHAR(255) NULL COMMENT '所有者岗位名称';
ALTER TABLE AIPRO_QJDST ADD CREATE_POS_CODE VARCHAR(255) NULL COMMENT '创建人岗位编码';
ALTER TABLE AIPRO_QJDST ADD CREATE_POS_NAME VARCHAR(255) NULL COMMENT '创建人岗位名称';
ALTER TABLE AIPRO_QJDST ADD OWNER_STAFF_CODE VARCHAR(50) NULL COMMENT '所有者员工编码';
ALTER TABLE AIPRO_QJDST ADD OWNER_STAFF_NAME VARCHAR(250) NULL COMMENT '所有者员工名称';
ALTER TABLE AIPRO_QJDST ADD DELETE_STAFF_CODE VARCHAR(50) NULL COMMENT '删除人编码';
ALTER TABLE AIPRO_QJDST ADD DELETE_STAFF_NAME VARCHAR(250) NULL COMMENT '删除人名称';
ALTER TABLE AIPRO_QJDST ADD MODIFY_STAFF_CODE VARCHAR(50) NULL COMMENT '修改人编码';
ALTER TABLE AIPRO_QJDST ADD MODIFY_STAFF_NAME VARCHAR(250) NULL COMMENT '修改人名称';
ALTER TABLE AIPRO_QJDST ADD CREATE_STAFF_CODE VARCHAR(50) NULL COMMENT '创建人编码';
ALTER TABLE AIPRO_QJDST ADD CREATE_STAFF_NAME VARCHAR(250) NULL COMMENT '创建人名称';
ALTER TABLE AIPRO_QJDST ADD OWNER_DEPT_CODE VARCHAR(255) NULL COMMENT '所有者部门编码';
ALTER TABLE AIPRO_QJDST ADD OWNER_DEPT_NAME VARCHAR(255) NULL COMMENT '所有者部门名称';
ALTER TABLE AIPRO_QJDST COMMENT = '请假单' ;
ALTER TABLE AIPRO_QJDST CHARACTER SET = utf8mb4  COLLATE = utf8mb4_bin;
