## 1773.8017.21888

CREATE TABLE AIPRO_SYS_COUNTER(
`ID` VARCHAR(32) NOT NULL , 
`NAME` VARCHAR(400),     
`TYPECODE` VARCHAR(400), 
`CATEGORY` VARCHAR(400), 
`PATTERN` VARCHAR(400),  
`VALUE` DECIMAL(20,0),     
`VERSION` DECIMAL(38,0),   
 PRIMARY KEY (`ID`)       
 );


CREATE TABLE AIPRO_SYS_BIZ_PRIMARY(
`ID` DECIMAL(19) NOT NULL PRIMARY KEY COMMENT '主键ID',
`MODULE_CODE` VARCHAR(32) NOT NULL COMMENT '模块编码',
`BIZ_ID` DECIMAL(19) NOT NULL COMMENT '业务主键ID',
`BIZ_TABLE` VARCHAR(128) NOT NULL COMMENT '业务表',
`BIZ_PRIMARY_VALUE` VARCHAR(400) NOT NULL COMMENT '业务主键值',
`VERSION` DECIMAL(19) NULL COMMENT '版本号' 
 );
CREATE UNIQUE INDEX UN_INDEX_AIPRO ON AIPRO_SYS_BIZ_PRIMARY(`BIZ_TABLE`,`BIZ_PRIMARY_VALUE`);
CREATE INDEX INDEX_AIPRO_BIZ_ID USING BTREE ON AIPRO_SYS_BIZ_PRIMARY(`BIZ_ID`);
ALTER TABLE AIPRO_SYS_BIZ_PRIMARY MODIFY COLUMN BIZ_PRIMARY_VALUE varchar(4000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '业务主键值';
CREATE TABLE aipro_WF_TASK(
`ID` DECIMAL(19) NOT NULL PRIMARY KEY, 
`TASK_NAME` VARCHAR(255),     
`TASK_NAME_I18N` VARCHAR(255),  
`TASK_ID` DECIMAL(19), 
`PROCESS_ID` VARCHAR(255), 
`USER_ID` DECIMAL(19),     
`USER_NAME` VARCHAR(255),   
`PERSON_CODE` VARCHAR(255),   
`PERSON_ID` DECIMAL(19),   
`NODE_ID` VARCHAR(255) 
 );
ALTER TABLE aipro_WF_TASK ADD CREATE_TIME TIMESTAMP(3) NULL;
ALTER TABLE aipro_WF_TASK ADD MODEL_CODE VARCHAR(255) NULL;
ALTER TABLE aipro_WF_TASK ADD TASK_TYPE VARCHAR(255) NULL;
ALTER TABLE aipro_WF_TASK ADD NODE_ID VARCHAR(255) NULL;
ALTER TABLE aipro_WF_TASK ADD NODE_TYPE VARCHAR(255) NULL;
CREATE INDEX IDX_AIPRO_PROCESS_ID ON aipro_WF_TASK (PROCESS_ID);

CREATE INDEX IDX_AIPRO_USER_NAME ON aipro_WF_TASK (USER_NAME);

CREATE INDEX IDX_AIPRO_MODEL_CODE ON aipro_WF_TASK (MODEL_CODE);
