## 1.0.0
CREATE TABLE AIPRO_QJDST(
"NAME" VARCHAR(510) NULL,
"NUM" VARCHAR(510) NULL,
"OPTIME" TIMESTAMP(6) NULL,
"GSNUM" DECIMAL(21,2) NULL,
"STARTTIME" TIMESTAMP(6) NULL,
"ENDTIME" TIMESTAMP(6) NULL,
"COMPANY_CODE" VARCHAR(255) NULL,
"CREATE_TIME" TIMESTAMP(6) NULL,
"MODIFY_TIME" TIMESTAMP(6) NULL,
"DELETE_TIME" TIMESTAMP(6) NULL,
"SORT" int8 NULL,
"PROCESS_KEY" VARCHAR(255) NULL,
"PROCESS_ID" VARCHAR(255) NULL,
"FORM_NO" VARCHAR(255) NULL,
"PROCESS_TASK_I18N" VARCHAR(255) NULL,
"PROCESS_STATUS" VARCHAR(50) NULL,
"PROCESS_NAME" VARCHAR(100) NULL,
"PROCESS_VERSION" VARCHAR(20) NULL,
"EFFECT_TIME" TIMESTAMP(6) NULL,
"ID" int8 NOT NULL PRIMARY KEY,
"VERSION" int8 NULL,
"VALID" int8 DEFAULT 1 NOT NULL,
"POS_LAY_REC" VARCHAR(255) NULL,
"OWNER_POS_CODE" VARCHAR(255) NULL,
"OWNER_POS_NAME" VARCHAR(255) NULL,
"CREATE_POS_CODE" VARCHAR(255) NULL,
"CREATE_POS_NAME" VARCHAR(255) NULL,
"OWNER_STAFF_CODE" VARCHAR(50) NULL,
"OWNER_STAFF_NAME" VARCHAR(250) NULL,
"DELETE_STAFF_CODE" VARCHAR(50) NULL,
"DELETE_STAFF_NAME" VARCHAR(250) NULL,
"MODIFY_STAFF_CODE" VARCHAR(50) NULL,
"MODIFY_STAFF_NAME" VARCHAR(250) NULL,
"CREATE_STAFF_CODE" VARCHAR(50) NULL,
"CREATE_STAFF_NAME" VARCHAR(250) NULL,
"OWNER_DEPT_CODE" VARCHAR(255) NULL,
"OWNER_DEPT_NAME" VARCHAR(255) NULL
);
ALTER TABLE AIPRO_QJDST ADD NAME VARCHAR(510) NULL;
ALTER TABLE AIPRO_QJDST ADD NUM VARCHAR(510) NULL;
ALTER TABLE AIPRO_QJDST ADD OPTIME TIMESTAMP(6) NULL;
ALTER TABLE AIPRO_QJDST ADD GSNUM DECIMAL(21,2) NULL;
ALTER TABLE AIPRO_QJDST ADD STARTTIME TIMESTAMP(6) NULL;
ALTER TABLE AIPRO_QJDST ADD ENDTIME TIMESTAMP(6) NULL;
ALTER TABLE AIPRO_QJDST ADD COMPANY_CODE VARCHAR(255) NULL;
ALTER TABLE AIPRO_QJDST ADD CREATE_TIME TIMESTAMP(6) NULL;
ALTER TABLE AIPRO_QJDST ADD MODIFY_TIME TIMESTAMP(6) NULL;
ALTER TABLE AIPRO_QJDST ADD DELETE_TIME TIMESTAMP(6) NULL;
ALTER TABLE AIPRO_QJDST ADD SORT int8 NULL;
ALTER TABLE AIPRO_QJDST ADD PROCESS_KEY VARCHAR(255) NULL;
ALTER TABLE AIPRO_QJDST ADD PROCESS_ID VARCHAR(255) NULL;
ALTER TABLE AIPRO_QJDST ADD FORM_NO VARCHAR(255) NULL;
ALTER TABLE AIPRO_QJDST ADD PROCESS_TASK_I18N VARCHAR(255) NULL;
ALTER TABLE AIPRO_QJDST ADD PROCESS_STATUS VARCHAR(50) NULL;
ALTER TABLE AIPRO_QJDST ADD PROCESS_NAME VARCHAR(100) NULL;
ALTER TABLE AIPRO_QJDST ADD PROCESS_VERSION VARCHAR(20) NULL;
ALTER TABLE AIPRO_QJDST ADD EFFECT_TIME TIMESTAMP(6) NULL;
ALTER TABLE AIPRO_QJDST ADD ID int8 NULL PRIMARY KEY;
ALTER TABLE AIPRO_QJDST MODIFY ID int8 NOT NULL PRIMARY KEY;
ALTER TABLE AIPRO_QJDST ADD VERSION int8 NULL;
ALTER TABLE AIPRO_QJDST ADD VALID int8 DEFAULT 1 NULL;
ALTER TABLE AIPRO_QJDST MODIFY VALID int8 DEFAULT 1 NOT NULL;
ALTER TABLE AIPRO_QJDST ADD POS_LAY_REC VARCHAR(255) NULL;
ALTER TABLE AIPRO_QJDST ADD OWNER_POS_CODE VARCHAR(255) NULL;
ALTER TABLE AIPRO_QJDST ADD OWNER_POS_NAME VARCHAR(255) NULL;
ALTER TABLE AIPRO_QJDST ADD CREATE_POS_CODE VARCHAR(255) NULL;
ALTER TABLE AIPRO_QJDST ADD CREATE_POS_NAME VARCHAR(255) NULL;
ALTER TABLE AIPRO_QJDST ADD OWNER_STAFF_CODE VARCHAR(50) NULL;
ALTER TABLE AIPRO_QJDST ADD OWNER_STAFF_NAME VARCHAR(250) NULL;
ALTER TABLE AIPRO_QJDST ADD DELETE_STAFF_CODE VARCHAR(50) NULL;
ALTER TABLE AIPRO_QJDST ADD DELETE_STAFF_NAME VARCHAR(250) NULL;
ALTER TABLE AIPRO_QJDST ADD MODIFY_STAFF_CODE VARCHAR(50) NULL;
ALTER TABLE AIPRO_QJDST ADD MODIFY_STAFF_NAME VARCHAR(250) NULL;
ALTER TABLE AIPRO_QJDST ADD CREATE_STAFF_CODE VARCHAR(50) NULL;
ALTER TABLE AIPRO_QJDST ADD CREATE_STAFF_NAME VARCHAR(250) NULL;
ALTER TABLE AIPRO_QJDST ADD OWNER_DEPT_CODE VARCHAR(255) NULL;
ALTER TABLE AIPRO_QJDST ADD OWNER_DEPT_NAME VARCHAR(255) NULL;
COMMENT ON COLUMN AIPRO_QJDST.NAME IS '姓名';
COMMENT ON COLUMN AIPRO_QJDST.NUM IS '工号';
COMMENT ON COLUMN AIPRO_QJDST.OPTIME IS '入职时间';
COMMENT ON COLUMN AIPRO_QJDST.GSNUM IS '可用假期';
COMMENT ON COLUMN AIPRO_QJDST.STARTTIME IS '请假开始时间';
COMMENT ON COLUMN AIPRO_QJDST.ENDTIME IS '请假结束时间';
COMMENT ON COLUMN AIPRO_QJDST.COMPANY_CODE IS '公司编码';
COMMENT ON COLUMN AIPRO_QJDST.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN AIPRO_QJDST.MODIFY_TIME IS '修改时间';
COMMENT ON COLUMN AIPRO_QJDST.DELETE_TIME IS '删除时间';
COMMENT ON COLUMN AIPRO_QJDST.SORT IS '排序';
COMMENT ON COLUMN AIPRO_QJDST.PROCESS_KEY IS '流程key';
COMMENT ON COLUMN AIPRO_QJDST.PROCESS_ID IS '流程实例id';
COMMENT ON COLUMN AIPRO_QJDST.FORM_NO IS '流程单据编号';
COMMENT ON COLUMN AIPRO_QJDST.PROCESS_TASK_I18N IS '流程单据状态';
COMMENT ON COLUMN AIPRO_QJDST.PROCESS_STATUS IS '流程状态';
COMMENT ON COLUMN AIPRO_QJDST.PROCESS_NAME IS '流程名称';
COMMENT ON COLUMN AIPRO_QJDST.PROCESS_VERSION IS '流程版本';
COMMENT ON COLUMN AIPRO_QJDST.EFFECT_TIME IS '生效时间';
COMMENT ON COLUMN AIPRO_QJDST.ID IS '主键ID';
COMMENT ON COLUMN AIPRO_QJDST.VERSION IS '版本号';
COMMENT ON COLUMN AIPRO_QJDST.VALID IS '是否有效';
COMMENT ON COLUMN AIPRO_QJDST.POS_LAY_REC IS '岗位层级';
COMMENT ON COLUMN AIPRO_QJDST.OWNER_POS_CODE IS '所有者岗位编码';
COMMENT ON COLUMN AIPRO_QJDST.OWNER_POS_NAME IS '所有者岗位名称';
COMMENT ON COLUMN AIPRO_QJDST.CREATE_POS_CODE IS '创建人岗位编码';
COMMENT ON COLUMN AIPRO_QJDST.CREATE_POS_NAME IS '创建人岗位名称';
COMMENT ON COLUMN AIPRO_QJDST.OWNER_STAFF_CODE IS '所有者员工编码';
COMMENT ON COLUMN AIPRO_QJDST.OWNER_STAFF_NAME IS '所有者员工名称';
COMMENT ON COLUMN AIPRO_QJDST.DELETE_STAFF_CODE IS '删除人编码';
COMMENT ON COLUMN AIPRO_QJDST.DELETE_STAFF_NAME IS '删除人名称';
COMMENT ON COLUMN AIPRO_QJDST.MODIFY_STAFF_CODE IS '修改人编码';
COMMENT ON COLUMN AIPRO_QJDST.MODIFY_STAFF_NAME IS '修改人名称';
COMMENT ON COLUMN AIPRO_QJDST.CREATE_STAFF_CODE IS '创建人编码';
COMMENT ON COLUMN AIPRO_QJDST.CREATE_STAFF_NAME IS '创建人名称';
COMMENT ON COLUMN AIPRO_QJDST.OWNER_DEPT_CODE IS '所有者部门编码';
COMMENT ON COLUMN AIPRO_QJDST.OWNER_DEPT_NAME IS '所有者部门名称';
COMMENT ON TABLE AIPRO_QJDST IS '请假单';