## 1773.8017.21888

CREATE TABLE AIPRO_SYS_COUNTER(
"ID" CHAR(32) NOT NULL ENABLE, 
"NAME" VARCHAR2(400),     
"TYPECODE" VARCHAR2(400), 
"CATEGORY" VARCHAR2(400), 
"PATTERN" VARCHAR2(400),  
"VALUE" NUMBER(20,0),     
"VERSION" NUMBER(38,0),   
 PRIMARY KEY ("ID")       
 );


CREATE TABLE AIPRO_SYS_BIZ_PRIMARY(
"ID" NUMBER(19) NOT NULL PRIMARY KEY,
"MODULE_CODE" VARCHAR2(32) NOT NULL,
"BIZ_ID" NUMBER(19) NOT NULL,
"BIZ_TABLE" VARCHAR2(128) NOT NULL,
"BIZ_PRIMARY_VALUE" VARCHAR2(400) NOT NULL,
"VERSION" NUMBER(19) NULL 
 );
CREATE UNIQUE INDEX UN_INDEX_AIPRO ON AIPRO_SYS_BIZ_PRIMARY("BIZ_TABLE","BIZ_PRIMARY_VALUE");
COMMENT ON COLUMN AIPRO_SYS_BIZ_PRIMARY.ID IS '主键ID';
COMMENT ON COLUMN AIPRO_SYS_BIZ_PRIMARY.MODULE_CODE IS '模块编码';
COMMENT ON COLUMN AIPRO_SYS_BIZ_PRIMARY.BIZ_ID IS '业务主键ID';
COMMENT ON COLUMN AIPRO_SYS_BIZ_PRIMARY.BIZ_TABLE IS '业务表';
COMMENT ON COLUMN AIPRO_SYS_BIZ_PRIMARY.BIZ_PRIMARY_VALUE IS '业务主键值';
COMMENT ON COLUMN AIPRO_SYS_BIZ_PRIMARY.VERSION IS '版本号';
ALTER TABLE AIPRO_SYS_BIZ_PRIMARY MODIFY BIZ_PRIMARY_VALUE VARCHAR2(4000);
CREATE TABLE aipro_WF_TASK(
"ID" NUMBER(19) NOT NULL PRIMARY KEY, 
"TASK_NAME" VARCHAR2(255),     
"TASK_NAME_I18N" VARCHAR2(255),  
"TASK_ID" NUMBER(19), 
"PROCESS_ID" VARCHAR2(255), 
"USER_ID" NUMBER(19),     
"USER_NAME" VARCHAR2(255),   
"PERSON_CODE" VARCHAR2(255),   
"PERSON_ID" NUMBER(19),   
"NODE_ID" VARCHAR2(255) 
 );
ALTER TABLE aipro_WF_TASK ADD CREATE_TIME TIMESTAMP(3) NULL;
ALTER TABLE aipro_WF_TASK ADD MODEL_CODE VARCHAR2(255) NULL;
ALTER TABLE aipro_WF_TASK ADD TASK_TYPE VARCHAR2(255) NULL;
ALTER TABLE aipro_WF_TASK ADD NODE_ID VARCHAR2(255) NULL;
ALTER TABLE aipro_WF_TASK ADD NODE_TYPE VARCHAR2(255) NULL;
CREATE INDEX IDX_AIPRO_PROCESS_ID ON aipro_WF_TASK (PROCESS_ID);

CREATE INDEX IDX_AIPRO_USER_NAME ON aipro_WF_TASK (USER_NAME);

CREATE INDEX IDX_AIPRO_MODEL_CODE ON aipro_WF_TASK (MODEL_CODE);
