## 1773.8017.21889

CREATE TABLE AIPRO_SYS_COUNTER(
"ID" CHAR(32) NOT NULL , 
"NAME" VARCHAR(400),     
"TYPECODE" VARCHAR(400), 
"CATEGORY" VARCHAR(400), 
"PATTERN" VARCHAR(400),  
"VALUE" int8,     
"VERSION" int4,   
 PRIMARY KEY ("ID")       
 );


CREATE TABLE AIPRO_SYS_BIZ_PRIMARY(
"ID" int8 NOT NULL PRIMARY KEY,
"MODULE_CODE" VARCHAR(32) NOT NULL,
"BIZ_ID" int8 NOT NULL,
"BIZ_TABLE" VARCHAR(128) NOT NULL,
"BIZ_PRIMARY_VALUE" VARCHAR(400) NOT NULL,
"VERSION" int4 NULL 
 );
CREATE UNIQUE INDEX UN_INDEX_AIPRO ON AIPRO_SYS_BIZ_PRIMARY("BIZ_TABLE","BIZ_PRIMARY_VALUE");
COMMENT ON COLUMN AIPRO_SYS_BIZ_PRIMARY.ID IS '主键ID';
COMMENT ON COLUMN AIPRO_SYS_BIZ_PRIMARY.MODULE_CODE IS '模块编码';
COMMENT ON COLUMN AIPRO_SYS_BIZ_PRIMARY.BIZ_ID IS '业务主键ID';
COMMENT ON COLUMN AIPRO_SYS_BIZ_PRIMARY.BIZ_TABLE IS '业务表';
COMMENT ON COLUMN AIPRO_SYS_BIZ_PRIMARY.BIZ_PRIMARY_VALUE IS '业务主键值';
COMMENT ON COLUMN AIPRO_SYS_BIZ_PRIMARY.VERSION IS '版本号';
ALTER TABLE AIPRO_SYS_BIZ_PRIMARY MODIFY BIZ_PRIMARY_VALUE VARCHAR(4000);
CREATE TABLE aipro_WF_TASK(
"ID" int8 NOT NULL PRIMARY KEY, 
"TASK_NAME" VARCHAR(255),     
"TASK_NAME_I18N" VARCHAR(255),  
"TASK_ID" NUMBER(19), 
"PROCESS_ID" VARCHAR(255), 
"USER_ID" int8,     
"USER_NAME" VARCHAR(255),   
"PERSON_CODE" VARCHAR(255),   
"PERSON_ID" int8,   
"NODE_ID" VARCHAR(255) 
 );
ALTER TABLE aipro_WF_TASK ADD CREATE_TIME TIMESTAMP(3) NULL;
ALTER TABLE aipro_WF_TASK ADD MODEL_CODE VARCHAR(255) NULL;
ALTER TABLE aipro_WF_TASK ADD TASK_TYPE VARCHAR(255) NULL;
ALTER TABLE aipro_WF_TASK ADD NODE_ID VARCHAR(255) NULL;
ALTER TABLE aipro_WF_TASK ADD NODE_TYPE VARCHAR(255) NULL;
CREATE INDEX IDX_AIPRO_PROCESS_ID ON aipro_WF_TASK (PROCESS_ID);

CREATE INDEX IDX_AIPRO_USER_NAME ON aipro_WF_TASK (USER_NAME);

CREATE INDEX IDX_AIPRO_MODEL_CODE ON aipro_WF_TASK (MODEL_CODE);
